name: Periodic JSON Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
    - cron: '0 * * * *'     # Every hour

permissions:
  contents: write  # Allow write access to repository contents

jobs:
  update-all-json-every-3-hours:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Axios
        run: npm install axios

      - name: Update JSON Files Every 3 Hours
        run: |
          node script/fetch-all.js

      - name: Fetch and Merge Latest Changes from Remote Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch latest changes from the remote git-bot-spam branch
          git fetch origin git-bot-spam

          # Checkout the target branch
          git checkout git-bot-spam

          # Merge the remote changes into the local branch
          git merge origin/git-bot-spam --no-edit || echo "Merge conflicts detected, skipping commit"

          # Add all changes
          git add .

          # Commit if there are any changes
          if ! git diff --cached --quiet; then
            git commit -m "Updated JSON files every 3 hours"
            git push origin git-bot-spam
          else
            echo "No changes to commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-headline-json-every-1-hour:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Axios
        run: npm install axios

      - name: Update JSON File Every 1 Hour
        run: |
          node script/fetch-headline.js

      - name: Fetch and Merge Latest Changes from Remote Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch latest changes from the remote git-bot-spam branch
          git fetch origin git-bot-spam

          # Checkout the target branch
          git checkout git-bot-spam

          # Merge the remote changes into the local branch
          git merge origin/git-bot-spam --no-edit || echo "Merge conflicts detected, skipping commit"

          # Add all changes
          git add .

          # Commit if there are any changes
          if ! git diff --cached --quiet; then
            git commit -m "Updated Headline JSON file every 1 hour"
            git push origin git-bot-spam
          else
            echo "No changes to commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
